### ISSUE TITLE
access to training code

### ISSUE THREAD

**Issue by jjeremy40** [dororojames/ANFIC#1]
Hi !
Very nice code you have there !
Could it be possible to have access to the training code to reproduce the results ?

Thanks in advance for your answer.

**Comment by jjeremy40** [comment]
Please ?

**Comment by jjeremy40** [comment]
Hi, i'm sorry but i'm encountering multiple issues with your code...

I'm trying to reproduce your results on Kodak images using the methods 'compress' and decompress of AugmentedNormalizedFlowHyperPriorCoder in network, but I get strange results such as a compression rate of 18 bpp which is enormous....

Can you help ?
Thanks.

**Comment by dororojames** [comment]
> Hi, i'm sorry but i'm encountering multiple issues with your code...
> 
> I'm trying to reproduce your results on Kodak images using the methods 'compress' and decompress of AugmentedNormalizedFlowHyperPriorCoder in network, but I get strange results such as a compression rate of 18 bpp which is enormous....
> 
> Can you help ? Thanks.

Sorry for the late reply, I've been out of the lab for a few months, so I won't officially support this project.
  In response to your training code request, I'm sorry I'm not authorized to distribute our training code, but you can refer to CompressAI's training code.
  Second, you said you have some problems with compress and decompress, I have to say that I am currently testing pytorch==1.4.0, and other related packages required by require.txt.
  So I suggest you to check your pytorch environment first.

BR.
James

**Comment by jjeremy40** [comment]
Hi, thanks you so much for your response !
I'm currently using pytorch==1.7.1,can it really be the source of the problem ??

I'm using precisly your command line and I did not touch your code.
To Compress :
`python .\ANFIC_codec.py -UC -C GaussianMixtureModel -NF 320 -VNFL 128 -QE -DM compress -ckpt .\models\ANFIC_R0.ckpt -SD .\example_image\ --eval`

This is the output : 
![2022-03-25 18_14_55-Administrator_ PowerShell 7 (x64)](https://user-images.githubusercontent.com/44731689/160170427-10caa7f7-a0ce-498a-b9ca-4b2e3a937c60.png)

And then to Decompress : 
`python .\ANFIC_codec.py -UC -C GaussianMixtureModel -NF 320 -VNFL 128 -QE -DM decompress -ckpt .\models\ANFIC_R0.ckpt -SD .\example_image\ -TD .\recon\ --eval -OD .\example_image\`

This is the output and the reconstructed img : 
![2022-03-25 18_17_59-Administrator_ PowerShell 7 (x64)](https://user-images.githubusercontent.com/44731689/160170616-827050e6-5e4d-46ad-baa7-c9289860338c.png)
![kodim01](https://user-images.githubusercontent.com/44731689/160170630-7cdc0076-6c8b-4362-b8da-e1b7b86b148f.png)


It is pretty but not really what's expected...
And a compression rate at 18 bits per pixel thats crazy !

**Comment by dororojames** [comment]
> Hi, thanks you so much for your response ! I'm currently using pytorch==1.7.1,can it really be the source of the problem ??
> 
> I'm using precisly your command line and I did not touch your code. To Compress : `python .\ANFIC_codec.py -UC -C GaussianMixtureModel -NF 320 -VNFL 128 -QE -DM compress -ckpt .\models\ANFIC_R0.ckpt -SD .\example_image\ --eval`
> 
> This is the output : ![2022-03-25 18_14_55-Administrator_ PowerShell 7 (x64)](https://user-images.githubusercontent.com/44731689/160170427-10caa7f7-a0ce-498a-b9ca-4b2e3a937c60.png)
> 
> And then to Decompress : `python .\ANFIC_codec.py -UC -C GaussianMixtureModel -NF 320 -VNFL 128 -QE -DM decompress -ckpt .\models\ANFIC_R0.ckpt -SD .\example_image\ -TD .\recon\ --eval -OD .\example_image\`
> 
> This is the output and the reconstructed img : ![2022-03-25 18_17_59-Administrator_ PowerShell 7 (x64)](https://user-images.githubusercontent.com/44731689/160170616-827050e6-5e4d-46ad-baa7-c9289860338c.png) ![kodim01](https://user-images.githubusercontent.com/44731689/160170630-7cdc0076-6c8b-4362-b8da-e1b7b86b148f.png)
> 
> It is pretty but not really what's expected... And a compression rate at 18 bits per pixel thats crazy !

Like I said, I only verified this repo with torch==1.4.0 .  It seems that from 1.7.0 onwards our framework will have some issues with the ac backend, so compression and decompression will crash.
  So here is my suggestion, you can create an environment with torch1.4.0 for this repo, otherwise you can just take our model weights and reimplement ANFIC for 1.7.0.
BR
James

**Comment by jjeremy40** [comment]
Ok I'll try that ! Thanks again for the help.
Cheers.

**Comment by jjeremy40** [comment]
It works ! thanks
