### ISSUE TITLE
Multiple Issues while running codes

### ISSUE THREAD

**Issue by sri-abhinav** [dororojames/ANFIC#2]
@dororojames @jjeremy40

Hi, I tried to replicate and follow the steps mentioned in 'ReadMe' to get the results but, I got multiple errors related to the environment and library issues. I created the specific PyTorch==1.4.0 environment and worked on that only. If you could please share a step-by-step guide for this work or how exactly you executed the commands and got results, it would be a great help.

Thank you.
Abhinav

**Comment by dororojames** [comment]
Hello Abhinav,Thanks for your info.This project was implemented with pytorch 1.4.0, and needs to build the arithmetic coding module for compression.I do not maintaining this project for a long time, I might not help too much.If you don’t mind, could you please share the error message ?BRJames ChanAbhinav Kumar Srivastava ***@***.***> 於 2024年4月1日 清晨6:40 寫道：﻿
@dororojames @jjeremy40
Hi, I tried to replicate and follow the steps mentioned in 'ReadMe' to get the results but, I got multiple errors related to the environment and library issues. I do not know if that is something specific to the old torch version and Python environment. If you could please share a step-by-step guide for this work or some insights into how exactly you executed the commands and got results, it would be helpful.
Thank you.
Abhinav

**Comment by sri-abhinav** [comment]
Thanks for your response. I get this when I run the first command to evaluate:
![Import Error](https://github.com/dororojames/ANFIC/assets/121310150/6cd9dbf3-f955-413f-9eb8-a9b056f2b152)

**Comment by dororojames** [comment]
Hi Abhinav,According to your log, it seems like your pytorch doesn’t install successfully, please first check about your environment, thanks.BRJames ChanAbhinav Kumar Srivastava ***@***.***> 於 2024年4月1日 晚上9:09 寫道：﻿
Thanks for your response. I get this when I run the first command to evaluate:
Import.Error.png (view on web)

**Comment by sri-abhinav** [comment]
Hi James, so as you suggested I checked my environment and it is pytorch 1.4.0 with torchvision 0.5.0. Since I installed the CPU only computed command from PyTorch library, it shows an error: 'No CUDA runtime is found' and some more errors related to 'torchac'. If you could please tell me what could be the problem? I used Windows OS, doesn't seem to be a problem right?

@jjeremy40: Hi, 
Would you please share some information about how you were able to successfully perform and run all the commands?

**Comment by dororojames** [comment]
Hi Abhinav,According to your log, it seems like your pytorch doesn’t install successfully, please first check about your environment, thanks.BRJames ChanAbhinav Kumar Srivastava ***@***.***> 於 2024年4月1日 晚上9:09 寫道：﻿
Thanks for your response. I get this when I run the first command to evaluate:
Import.Error.png (view on web)

**Comment by sri-abhinav** [comment]
It worked now, thanks.
